name: CI Checks

on:
  pull_request:
    branches: [main, dev, qa, prod]  # Trigger on PRs to these branches

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run lint
        run: |
          flake8 . || true  # Allow non-zero exit for testing setup

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Run tests
        run: |
          echo "Running tests here"
          # Add pytest or unittest here
          # pytest tests/

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build step
        run: echo "Build successful"  # Replace with your actual build command
name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev, qa, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run tests
        run: |
          echo "Run your tests here"
          # pytest or unittest

